mikeleguedes/json-movie-list

movies/2018/love-simon.json

love, simon. Adding movie.

---

actors/barbara-colen.json
actors/sonia-braga.json
actors/udo-kier.json
directors/kleber-mendoca-filho.json
movies/2019/bacurau.json

bacurau movie

---

movies/2019/us.json

Adding the details for the movie Us

---

movies/2019/pokemon-detective-pikachu.json

pokemon-detective-pikachu

---

movies/2019/marvel-avengers-endgame.json

marvel-avengers-endgame

---

movies/2018/maze-runner-the-death-cure.json

Adds Maze Runner: The Death Cure movie
Closes #39

Add Maze Runner: The Death Cure movie

---

movies/2019/aladdin.json

Issue #24 - Added in Aladdin Movie for 2019.

Issue #24 - Added Aladdin -2019

---

movies/2019/dark-phoenix.json

dark phoenix file added to folder 2019 movie #27

dark phoenix file added movie #27

---

movies/1939/the-wizard-of-oz.json

Added The Wizard of Oz #110 

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md

add issue templates for new issue workflow

---

movies/2019/aladdin.json
movies/2019/toy-story-4.json

ISSUE #35 - Added Toy story 4 movie to 2019 folder.

ISSUE #35 - Toy story 4 movie

---

movies/2019/after.json

Add movie "After" from 2019

---

movies/2019/the-curse-of-la-llorona.json

Added The Curse of La Llorona #19

---

movies/2019/spider-man-far-from-home.json

add spider man movie details

---

movies/2019/the-lion-king.json

#38 The lion king

---

movies/2018/a-quiet-place.json

Added A Quiet Place

---

movies/2004/the-phantom-of-the-opera.json

Fixes #86 
Here for hacktoberfest so please merge soon if possible! :)

Add Phantom of the Opera

---

movies/1938/the-adventures-of-robin-hood.json

Movie: Added The Adventures of Robin Hood (1938)

---

movies/1985/after-hours.json

Add the movie After Hours

---

movies/2016/hacksaw-ridge.json

#120 fixed quotation marks in description

Fix the quotation marks on Hacksaw Ridge movie

---

movies/2005/the-hitchhikers-guide-to-the-galaxy.json

Add The Hitchhiker's Guide to the Galaxy to 2005 movie list.

Add The Hitchhiker's Guide to the Galaxy

---

movies/1942/casablanca.json

Added 1942 folder and casablanca movie into database.
Cheers! ;)

Added casablanca movie to movies folder

---

actors/aubrey-plaza.json
movies/1984/purple-rain.json

Added Aubrey Plaza to actors and Purple Rain to movies

2 Additions

---

movies/1999/pretty-woman.json

Add Pretty Woman

---

movies/2005/pride-and-prejudice.json

Add Pride & Prejudice to the 2005 movie list.

Add Pride & Prejudice

---

movies/2019/angel-has-fallen.json

Add Angel Has Fallen on the list.

Add Angel Has Fallen movie

---

movies/2017/the-invisible-man.js

added The Invisible Man info. Let me know if any changes are required.

added The Invisible Man

---

directors/anthony-russo.json
directors/joseph-russo.json
directors/ric-roman-waugh.json
directors/tim-miller.json

Add Ric Roman Waugh, Russo Brothers and Tim Miller to Director List

Add 4 Directors to Director List

---

movies/2018/ocean-8.json
movies/2018/oceans-8.json

Added Ocean's 8

---

actors/colin-ford.json
actors/jude-law.json
actors/kenneth-mitchell.json

Add Jude Law, Colin Ford and Kenneth Mitchell to Actor list

Add new Actors to Actor list

---

movies/1989/dead-poets-society.json

Fixes #140: Added Dead Poets Society movie

Fixes #140: Added Dead Poets Society movie

---

movies/2019/hobbs-&-shaw.json
movies/2019/hobbs-&-show.json

Added the movie Hobbs & Show to the 2019 folder

Added movie Hobbs & Show

---

movies/2005/walk-the-line.json

Add Walk the Line to the 2005 movie list.

Add Walk the Line

---

movies/1925/the-wizard-of-oz.json

Movie: Added The Wizard of Oz (1925)

---

movies/2019/it-chapter-two.json

add movie info

---

actors/ayelet-zurer.json
actors/bill-skarsgard.json
actors/cristin-milioti.json
actors/kate-beckinsale.json
actors/keira-knightley.json
actors/krysten-ritter.json
actors/tom-holland.json
movies/2002/resident-evil.json
movies/2004/resident-evil-2-apocalypse.json
movies/2007/resident-evil-3-extinction.json
movies/2010/due-date.json
movies/2010/resident-evil-4-afterlife.json
movies/2012/resident-evil-5-retribution.json
movies/2016/resident-evil-6-final-chapter.json

I added all resident evil movies, due date movie (2010) and actors such as Ayelet Zurer, Bill Skarsgard, Kate Beckinsale, Keira Knightley, Krysten Ritter and Tom Holland.

Adding resident evil series, due date and some actors

---

movies/2019/lucy-in-the-sky.json

Added Lucy In The Sky movie to the 2019 movie list

AAdded Lucy in the sky movie

---

movies/2010/red.json

Submission of Red (2010)

---

movies/2001/a-beautiful-mind.json

Added the movie A Beautiful Mind in the movies from 2001.

Added the moive A beautiful mind

---

movies/2019/hustlers.json

Added the movie Hustlers to the list of movies from 2019.

Added the movie Hustlers

---

movies/2016/ah-ga-ssi.json

Adding Ah-ga-ssi to movie collection #198

---

directors/petra-costa.json

added petra-costa.json in directors

added petra-costa.json

---

directors/laís-bodanzky.json

adding laís bodanzky to directors list

---

movies/2019/first-cow.json

Added First Cow - 2019

---

directors/guel-arraes.json

Fixes #212 Guel Arraes added to the collection of directors #212

---

movies/2019/Vitalina-Varela.json

added Vitalina Varela 2019

---

directors/fernando-meirelles.json

adding fernando meirelles to directors list

---

movies/2014/what-we-do-in-the-shadows.json
movies/2019/jojo-rabbit.json

Add movies:
- What we do in the shadows
- Jojo Rabbit

Add what we do in the shadows and jojo rabbit from Taika Waititi

---

movies/2019/martin-eden.json

Added Martin Eden Movie.
This PR resolves, this https://github.com/mikeleguedes/json-movie-list/issues/225 issue.

feat: add martin eden movie

---

movies/2020/shirley.json

Created 2020 folder and added Shirley(2020)

---

movies/2020/da-5-blood.json

adding da 5 blood

---

movies/2020/the-invisible-man.json

I have created another folder "2020" inside of the movies folder and placed the JSON file inside.

Added "The Invisible Man" to the movies folder.

---

actors/daniel-olbrychski.json

daniel olbrychski

---

movies/1993/dragon-the-bruce-lee-story.json
movies/1993/hocus-pocus.json

Adding Hocus Pocus (1993) and fixing the runtime on Dragon the Bruce Lee Story - it read 1120 and should be 120.

Adding hocus pocus and fixing dragon

---

actors/bruce-boxleitner.json
actors/david-warner.json
actors/garrett-hedlund.json
actors/jeff-bridges.json
actors/olivia-wlde.json
directors/steven-lisberger.json
movies/1982/tron.json
movies/2010/tron-legacy.json

added actors and directors
Joseph Kosinski can be found in  #272 
Was not added for no merge conflicts

add Tron(1982) and Tron: Legacy(2010)

---

actors/millie-bobby-brown.json
actors/sam-claflin.json
movies/2020/enola-holmes.json

added actors
Due to no information on the director i left him out.

Add Enola Holmes (2020)

---

actors/miles-teller.json
directors/joseph-kosinski.json
movies/2022/top-gun-maverick.json

Add Top Gun: Maverick

---

actors/chiara-aurelia.json
actors/finn-wittrock.json
directors/mike-barker.json
movies/2022/luckiest-girl-alive.json

Add Luckiest Girl Alive(2022)

---

package.json
scraper/index.js
scraper/scraper.md

I wanted to resolve issue #292 this is a basic webscraper that gets information from the top 250 movies from IMDB but the code can easily be modified to do anything. So as more specific behaviors are requested anyone can add on to it and get that behavior.
in short, gets top 250 movies and ratings then outputs them into a log file in the same directory.

Created a web scraper for IMDB

---

movies/2021/malcolm-and-marie.json

Hey,
Just took my first steps in open source contribution! 👶🏼 
Thx for sharing this repo with us at the He4rtDelas meeting. 💜

add Malcolm and Marie

---

directors/wong-kar-wai.json
movies/1994/chungking-express.json
movies/1995/fallen-angels.json
movies/1997/happy-together.json
movies/2000/in-the-mood-for-love.json
movies/2004/2046.json

Hey! :octocat: 
I added the director Wong Kar-wai and five of his films, which are:
- In the Mood for Love (2000)
- Chungking Express (1994)
- Fallen Angels (1995)
- Happy Together (1997)
- 2046 (2004)
Please add hacktoberfest and hactoberfest-accepted label. Thank you!! 🧡

add director Wong Kar-wai and some of his films

---

directors/agnes-varda.json
movies/2023/killers-of-the-flower-moon.json

Added movie Killers of the Flower Moon (2023)! 🎦

Add Killers of the Flower Moon (2023)
